# Generated by Django 4.1.7 on 2023-03-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
